// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9f5TxwIex5sWvV0THboms9opRiCSImc0',
    appId: '1:654667186322:web:f325ab87165a9b4f84264b',
    messagingSenderId: '654667186322',
    projectId: 'cue-count',
    authDomain: 'cue-count.firebaseapp.com',
    storageBucket: 'cue-count.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA68yQqGK4_SluR1_5Kc0i5ZvWCMsSIH_E',
    appId: '1:654667186322:android:096df613c2da1f6684264b',
    messagingSenderId: '654667186322',
    projectId: 'cue-count',
    storageBucket: 'cue-count.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0j7iAKhr3u0zMEDpQX4DKnR1l362ky60',
    appId: '1:654667186322:ios:3496541882fb02a684264b',
    messagingSenderId: '654667186322',
    projectId: 'cue-count',
    storageBucket: 'cue-count.firebasestorage.app',
    iosBundleId: 'com.example.cueCount',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0j7iAKhr3u0zMEDpQX4DKnR1l362ky60',
    appId: '1:654667186322:ios:3496541882fb02a684264b',
    messagingSenderId: '654667186322',
    projectId: 'cue-count',
    storageBucket: 'cue-count.firebasestorage.app',
    iosBundleId: 'com.example.cueCount',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9f5TxwIex5sWvV0THboms9opRiCSImc0',
    appId: '1:654667186322:web:416214f6381e347c84264b',
    messagingSenderId: '654667186322',
    projectId: 'cue-count',
    authDomain: 'cue-count.firebaseapp.com',
    storageBucket: 'cue-count.firebasestorage.app',
  );
}
